version: '3.3'

services:
  db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
    volumes:
      - ${BACKUP_PATH}/mysql:/var/lib/mysql
    ports:
      - ${DB_PORT_EXPOSE}:3306
    networks:
      - laravel_auth

  php:
    build:
      context: ./docker/site
      args:
        - PHP_VERSION=${PHP_VERSION:-8.0}
    volumes:
      - ./:/var/www/site:cached
    networks:
      - laravel_auth

  nginx:
    image: nginx:alpine
    ports:
      - "${APP_PORT:-8299}:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./:/var/www/site:cached
    networks:
      - laravel_auth

networks:
  laravel_auth:
